services:
  distributor:
    container_name: "trud-distributor"
    build:
      context: .
      dockerfile: trud_distributor.Dockerfile
    environment:
      - CUSTOM_CONFIG_PATCH=/app/trud_distributor.prod.yaml
    volumes:
      - ./configs/trud_distributor/trud_distributor.prod.yaml:/app/trud_distributor.prod.yaml
    ports:
      - "8080:8080"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
    volumes:
      - ./configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/00-custom.conf  # the container initially defines the /etc/rabbitmq/conf.d/10-cust.conf, we immediately indicate the smaller file number, see: https://www.rabbitmq.com/docs/configure#config-confd-directory
      - ./configs/rabbitmq/definitions.json:/etc/rabbitmq/definitions/definitions.json # definition of Definitions is indicated in 00-custom.conf for key definitions.local.path
      - ./custom/rabbitmq_data:/var/lib/rabbitmq/
    restart: always
#volumes:
#  rabbitmq_data:  # Определяем том для данных
#
#networks:
#  rabbitmq_net: